set_water_level:
  name: Set Water Level
  description: "Sets the water level for the mop."
  fields:
    water_level:
      name: Water Level
      description: "The desired water level."
      required: true
      selector:
        select:
          options:
            - "Low"
            - "Medium"
            - "High"

set_mop_pattern:
  name: Set Mop Pattern
  description: "Sets the mopping pattern."
  fields:
    mop_pattern:
      name: Mop Pattern
      description: "The desired mopping pattern."
      required: true
      selector:
        select:
          options:
            - "Standard"
            - "Y-type"

reset_consumable:
  name: Reset Consumable
  description: "Resets the counter for a specific consumable."
  fields:
    consumable:
      name: Consumable
      description: "The consumable to reset."
      required: true
      selector:
        select:
          options:
            - "main_brush"
            - "side_brush"
            - "filter"
            - "mop"
